[package]
name = "githab-api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.15.0"
tokio = { version = "1.14.0", features = ["full"] }
